name: modul_anerkennung
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - gradio
      - raganything[all]
      - git+https://github.com/dgaida/llm_client.git
      - lightrag
      - openai
      - python-dotenv
      - pytest
